name: ifun
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.8

  # Estado y patrones de diseño
  flutter_bloc: ^9.1.1
  provider: ^6.0.5

  # Bluetooth
  flutter_reactive_ble: ^5.2.0

  # Permisos (última versión estable)
  #permission_handler: ^12.0.1
  
  permission_handler: ^11.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Si más adelante agregas assets o fonts
  #assets:
  #  - assets/images/

  #fonts:
    # - family: YourFont
    #   fonts:
    #     - asset: fonts/YourFont-Regular.ttf
